//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_Base
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application_Base()
        {
            this.DependencyMatrices = new HashSet<DependencyMatrix>();
            this.DependencyMatrices1 = new HashSet<DependencyMatrix>();
        }
    
        public int AppId { get; set; }
        public string Appl_name { get; set; }
        public bool Threaded { get; set; }
        public string Division { get; set; }
        public int SOID { get; set; }
        public int SLID { get; set; }
        public string Comments { get; set; }
    
        public virtual Service_Line_Base Service_Line_Base { get; set; }
        public virtual Service_Offering_Base Service_Offering_Base { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DependencyMatrix> DependencyMatrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DependencyMatrix> DependencyMatrices1 { get; set; }
    }
}
