//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzUtility
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TryandDieEntities : DbContext
    {
        public TryandDieEntities()
            : base("name=TryandDieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application_Base> Application_Base { get; set; }
        public virtual DbSet<DependencyMatrix> DependencyMatrices { get; set; }
        public virtual DbSet<Service_Line_Base> Service_Line_Base { get; set; }
        public virtual DbSet<Service_Offering_Base> Service_Offering_Base { get; set; }
    }
}
