//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzUtility
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EzUtilityEntities : DbContext
    {
        public EzUtilityEntities()
            : base("name=EzUtilityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ezApplication> ezApplications { get; set; }
        public virtual DbSet<ezCluster> ezClusters { get; set; }
        public virtual DbSet<ezEnvironment> ezEnvironments { get; set; }
        public virtual DbSet<ezServer> ezServers { get; set; }
        public virtual DbSet<ezServiceLine> ezServiceLines { get; set; }
        public virtual DbSet<ezType> ezTypes { get; set; }
    }
}
