//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class ezServer
    {
        public int id { get; set; }
        public string MachineName { get; set; }
        public string MachineDomain { get; set; }
        public int EnvironmentID { get; set; }
        public int ApplicationID { get; set; }
        public int ServiceLineID { get; set; }
        public int TypeID { get; set; }
        public int ClusterID { get; set; }
    
        public virtual ezApplication ezApplication { get; set; }
        public virtual ezEnvironment ezEnvironment { get; set; }
        public virtual ezServiceLine ezServiceLine { get; set; }
        public virtual ezType ezType { get; set; }
        public virtual ezCluster ezCluster { get; set; }
    }
}
